name: Disala RDP - Ngrok 008

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
      - name: Download And Extracting Ngrok
        run: |
          Invoke-WebRequest https://github.com/chamod12/RDP-Downloads/blob/main/ngrok.exe?raw=true -OutFile ngrok.exe
          Invoke-WebRequest https://raw.githubusercontent.com/chamod12/RDP-Downloads/main/start.bat -OutFile start.bat
          Invoke-WebRequest https://raw.githubusercontent.com/chamod12/RDP-Downloads/main/Uploads.bat -OutFile Uploads.bat
          copy ngrok.exe C:\Windows\System32

      - name: Download And Extract NSSM
        run: |
          Invoke-WebRequest https://github.com/chamod12/RDP-Downloads/blob/main/nssm.exe?raw=true -OutFile nssm.exe
          copy nssm.exe C:\Windows\System32

      - name: Connecting ngrok Account
        run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN_008 }}
          
      - name: Enabling RDP Access
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      - name: Creating Tunnel [CPU 2 Core - 7GB Ram - 256 SSD]
        run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok.exe tcp --region in 3389"'

      - name: Connect to RDP [Copy ip, username, password from here]
        run: cmd /c start.bat

      - name: Upload Softwares To Desktop
        run: cmd /c Uploads.bat

      - name: Keep RDP session alive
        run: |
          Invoke-WebRequest https://raw.githubusercontent.com/chamod12/RDP-Downloads/main/keep-alive.ps1 -OutFile keep-alive.ps1
          Start-Process powershell.exe -ArgumentList "-ExecutionPolicy Bypass -WindowStyle Hidden -File keep-alive.ps1" -Verb RunAs

      - name: Time Count
        run: |
          Invoke-WebRequest https://github.com/chamod12/RDP-Downloads/raw/main/loop.bat -OutFile loop.bat
          cmd /c loop.bat
